apiVersion: v1
data:
  drawer: "true"
  form: "true"
  showFormStructure: "true"
  drawerSize: large
kind: ConfigMap
metadata:
  name: template-aws-ram-resourceshare-card
  namespace: aws-ram-system
---
apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  name: template-aws-ram-resourceshare-card
  namespace: aws-ram-system
spec:
  actions:
  - template:
      apiVersion: templates.krateo.io/v1alpha1
      name: template-aws-ram-resourceshare-customform
      namespace: aws-ram-system
      resource: customforms
      verb: GET
  - template:
      apiVersion: core.krateo.io/v1alpha1
      name: aws-ram-resourceshare
      namespace: aws-ram-system
      resource: compositiondefinitions
      verb: DELETE
  app:
    template:
      color: ${ .getCompositionDefinition.status.conditions[] | select(.type == "Ready") | if .status == "False" then "orange" elif .status == "True" then "green" else "grey" end }
      content: Provision an AWS Ram ResourceShare via the ACK ram controller.
      icon: fa-brands fa-aws
      tags: aws-ram-system,0.1.1
      title: aws-ram-resourceshare
      status: ${ .getCompositionDefinition.status.conditions[] | select(.type == "Ready") | "Ready:" + .status }
      date: ${ .getCompositionDefinition.metadata.creationTimestamp }
  propsRef:
    name: template-aws-ram-resourceshare-card
    namespace: aws-ram-system
  type: card
  api:
  - name: getCompositionDefinition
    path: "/apis/core.krateo.io/v1alpha1/namespaces/aws-ram-system/compositiondefinitions/aws-ram-resourceshare"
    verb: GET
    headers:
    - 'Accept: application/json'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: template-aws-ram-resourceshare-customform
  namespace: aws-ram-system
data:
  onSubmitId: submit
  onSubmitVerb: POST
  payloadFormKey: spec
  redirectRoute: /compositions/${metadata.namespace}/${metadata.name}
  redirectTimeout: "50"
---
apiVersion: templates.krateo.io/v1alpha1
kind: CustomForm
metadata:
  name: template-aws-ram-resourceshare-customform
  namespace: aws-ram-system
spec:
  type: customform
  propsRef:
    name: template-aws-ram-resourceshare-customform
    namespace: aws-ram-system
  actions:
    - template:
        id: submit
        apiVersion: composition.krateo.io/v0-1-1
        verb: POST
        resource: awsramresourceshares
        payloadToOverride:
        - name: metadata.namespace
          value: ${ "aws-ram-system" }
  app:
    template:
      schema: ${ .getCRD | .spec.versions[] | select(.name == "v0-1-1") | .schema.openAPIV3Schema.properties.spec }
  api:
  - name: getCRD
    path: "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/awsramresourceshares.composition.krateo.io"
    verb: GET
    headers:
    - 'Accept: application/json'
